# Generated by Django 4.2 on 2023-04-10 23:45

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='produtos', variations={'thumbnail': (124, 124)}, verbose_name='Imagem'),
        ),
    ]
